travis:
  secure:
    BINSTAR_TOKEN: jokYgO+FoFc6S9tV4pI8IW8kKnEkHO+lwL/6GiGFburCDOQMoEwMMKyQeHac+P3y1Hg7UdFkoSn7/v5Xz2yWiOHg+pZwV96eCF/6T75l2D/GHpOVrTQMR8vZwVJGFTK7ZJ1e+/KnADYJE1PgE+uB+cEn3wbZs6C52XG6aHyTDQmUDxg7YqMtpkKLMDlByyyVhoKH4MBl7lum3pjD4pSJXT9Z6hF8BE48T2zkaSAoUYhd2nTaFa/GlMfnoHhLweXz09gTOIyccpnWRxT0BhLqRV1l3tUM7DccKy6bVECUTFgoWZ2e2c1ZMPbqTS1qT31C3Zvqdqlcs9cOmtgR+upLjtsgdYeusiUcLnzgOuL9ZHqQ4q6UTsNLvVyk1POBECFbloSuZGZsxvVt7ArtPWC9ZxVkTzRe64lyGsnBXvEylGYMJ0yJDzlIavgYLdM3Zr4E/0zqyiye2ph5s4ow8e8iVcupp3hIbJ7Y2knF9iIRJF/0U0ZQoR6Jv6aQ2Gz+8qenbVhQA2gPmrQyokU8reljRzQbRhpOzRZZfTmvESrw2bdEN0THUxUGs4k98SiLAnKls/7WfM1o2n102/8Ckqrx1rr3AASFDnxmquzQ9j2W4pbQncZIE7/g4BfC/qBjdqd68J/XScDr4+ucgakcfr7AcXN7y56aPilbVJh75id2UXY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
